language: go

go:
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

services:
  - mysql
  - postgresql

before_install:
  # install linting tools
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/fzipp/gocyclo

install:
  - go get -t -d ./...
  - go build ./...

before_script:
  - psql -U postgres -c 'CREATE DATABASE goose'
  - export POSTGRES_DATABASE_DSN='host=localhost sslmode=disable user=postgres dbname=goose'
  - mysql -u root -e 'CREATE DATABASE goose'
  - export MYSQL_DATABASE_DSN='root@tcp(localhost:3306)/goose'

script:
  # make sure code is properly formatted and simplified
  - gofmt -l -s .
  # check for possible uh ohs
  - go vet ./...
  # run tests checking for race conditions
  - go test ./... -v -race

after_success:
  # check possible styling errors
  - golint ./...
  # check for potentially complex functions
  - gocyclo -over 15 .
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
      go list ./... | xargs -n 1 -I{} curl http://godoc.org/-/refresh -d path={}
    fi
