language: go

go:
  - 1.3
  - 1.4

before_install:
  # install linting tools
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/fzipp/gocyclo

install:
  - go get -t ./lib/goose
  - go build ./lib/goose
  - go get -t ./cmd/goose
  - go build ./cmd/goose

script:
  # make sure code is properly formatted and simplified
  - gofmt -l -s .
  # check for possible uh ohs
  - go vet ./...
  # run tests checking for race conditions
  - go test ./lib/goose -v -race

after_success:
  # check possible styling errors
  - golint ./...
  # check for potentially complex functions
  - gocyclo -over 15 .
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
      go list ./... | xargs -n 1 -I{} curl http://godoc.org/-/refresh -d path={}
    fi
